[package]
name = "BookLauncher"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = { version = "0.8", features = ["v4_12"] }
libadwaita = { version = "0.6", features = ["v1_4"] }
glib = "0.19"
gio  = "0.19"
walkdir = "2"
epub = "2"
anyhow = "1"
